name: Grab a file

on:
  workflow_dispatch:
    inputs:
      fw_url:
        description: 'Direct Link to Zip (BL, AP, CP, CSC)'
        required: true
        type: string
      target_file:
        description: 'File inside the tar.md5 (e.g., boot.img.lz4, etc.)'
        required: true
        type: string

jobs:
  extract-task:
    runs-on: ubuntu-latest

    env:
      # Colors
      BLUE: '\033[0;34m'
      GREEN: '\033[0;32m'
      RED: '\033[0;31m'
      YELLOW: '\033[1;33m'
      NC: '\033[0m' # No color

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Archive
        run: |
          echo -e "${BLUE}==> Downloading firmware archive...${NC}"
          curl -L "${{ github.event.inputs.fw_url }}" -o fw_archive.zip
          echo -e "${GREEN}Download complete.${NC}"

      - name: Extract tar.md5 from ZIP
        run: |
          echo -e "${BLUE}==> Extracting the .tar.md5 file from ZIP...${NC}"
          unzip fw_archive.zip "*.tar.md5"

          echo -e "${YELLOW}Cleaning up ZIP file...${NC}"
          rm fw_archive.zip

          mv *.tar.md5 firmware.tar 2>/dev/null || true
          echo -e "${GREEN}ZIP processed.${NC}"

      - name: Extract Target File
        run: |
          echo -e "${BLUE}==> Searching for: ${YELLOW}${{ github.event.inputs.target_file }}${NC}"

          echo -e "${YELLOW}Extracting ${{ github.event.inputs.target_file }} from archive...${NC}"

          # Extracting
          tar -xf firmware.tar ${{ github.event.inputs.target_file }} 2>/dev/null || true

          if [ -f "${{ github.event.inputs.target_file }}" ]; then
            echo -e "${GREEN}SUCCESS: ${{ github.event.inputs.target_file }} extracted successfully.${NC}"
          else
            echo -e "${RED}ERROR: Target file not found in the archive!${NC}"
            tar -tf firmware.tar
            exit 1
          fi

      - name: Cleanup TAR
        run: |
          echo -e "${YELLOW}Cleaning up temporary TAR...${NC}"
          rm firmware.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.target_file }}
          path: ${{ github.event.inputs.target_file }}
